<?php

namespace P5\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUserByMail($mail)
	{
		$qb = $this->createQueryBuilder('u');

		$qb->where('u.email = :mail')
		   ->setParameter('mail', $mail);

		return $qb->getQuery() 	
				  ->getOneOrNullResult();
	}

	public function getUserByTicket($ticket)
	{
		$qb = $this->createQueryBuilder('u');

		$qb->where('u.ticket_password = :ticket_password')
		   ->setParameter('ticket_password' , $ticket);

		return $qb->getQuery()
				  ->getOneOrNullResult();
	}
}
