<?php

namespace P5\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUserByMail($mail)
	{
		$qb = $this->createQueryBuilder('u');

		$qb->where('u.email = :mail')
		   ->setParameter('mail', $mail);

		return $qb->getQuery() 	
				  ->getResult();
	}			  
}
