p5_todolist_view:
    path:    /home/todolist/{page}
    defaults:  
        _controller: P5TodolistBundle:todolist:index
        page: 1
    requirements:
        page: \d+    
   
p5_todolist_add:
    path:    /home/todolist/add
    defaults:
      _controller: P5TodolistBundle:todolist:add
    requirements:

p5_todolist_edit: 
    path: /home/todolist/edit/{id}
    defaults:
      _controller: P5TodolistBundle:todolist:edit
    requirements:
        membreid: \d+
        id: \d+

p5_todolist_delete:
    path: /home/todolist/delete/{id}
    defaults:
      _controller: P5TodolistBundle:todolist:delete
    requirements:
        membreid: \d+
        id: \d+

