# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    P5\UserBundle\Entity\User: sha512

  role_hierarchy:
      ROLE_MEMBER:       ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_MEMBER, ROLE_ALLOWED_TO_SWITCH]

  providers:
      principal:
          entity:  
              class: P5\UserBundle\Entity\User
              property: username  

  provider: principal
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    principal:
      pattern:    ^/
      anonymous:    true
      form_login:
        login_path: login
        check_path: login_check
        failure_path: login
        default_target_path: p5_core_home
      logout:
        path:       logout
        target:     login
  
  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
