p5_user_inscription:
    path:     /home/inscription
    defaults: { _controller: P5UserBundle:Security:inscription }

p5_user_editpass:
    path:    /home/profil/edit
    defaults: {_controller: P5UserBundle:Security:changePassword}

p5_user_resetpass:
    path: /home/resetpass
    defaults: {_controller: P5UserBundle:Security:resetPassword}