<?php

namespace P5\TodolistBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * todolistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class todolistRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTodolist($page, $nbPerPage, $member) {

		$query = $this->createQueryBuilder('a');

		$query
			  ->where('a.user = :user')
			  ->setParameter('user', $member)
		;

		$query
				->setFirstResult(($page - 1) * $nbPerPage)
				->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);

	}

}


