<?php

namespace P5\TodolistBundle\Repository;

/**
 * todolistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class todolistRepository extends \Doctrine\ORM\EntityRepository
{
}
